import type { Metadata } from "next";
import { Google_Sans_Flex, Figtree } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/shared/theme-provider";
import { LandingThemeLock } from "@/components/shared/landing-theme-lock";


const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
  display: 'swap',
  fallback: ['system-ui']
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  display: 'swap',
  fallback: ['system-ui']
});


export const metadata: Metadata = {
  title: "Kvali",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', // Standard favicon
    shortcut: '/shortcut-icon.png',
    apple: '/apple-touch-icon.png', // For iOS home screen
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${figtree.className}  antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LandingThemeLock />
          <main>{children}</main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
